<?php


namespace App\Models;


use App\core\Model;
use App\Helpers\AliasHelper;

class Category extends Model
{
    protected static $tableName = 'product_categories';

    protected static $fillable = ['name', 'alias'];

    public function save()
    {
        if (empty($this->alias)) {
            $this->alias = AliasHelper::translit($this->name);
        }
        return parent::save(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function __toString()
    {
        return $this->name;
    }


}