<?php


namespace App\Models;


use App\core\Model;
use App\Helpers\AliasHelper;
use App\Helpers\Debugger;

class Product extends Model
{
    protected static $fillable = ['name', 'category_id', 'brand_id', 'alias'];

    public function save()
    {
        if (empty($this->alias)) {
            $this->alias = AliasHelper::translit($this->name) . "_" . random_int(0, 1000);
        }
        return parent::save(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $name
     */
    public function __get($name)
    {
        if ($name == 'category') {
            return Category::findById($this->category_id);
        }
        if ($name == 'brand') {
            return Brand::findById($this->brand_id);
        }
        return null;

    }


}